# Generated by Django 4.2.3 on 2023-10-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_alter_customuser_first_name_certificateissuance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstudent',
            name='feedback',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='feedback_reply',
            field=models.FileField(upload_to=''),
        ),
    ]
